from numpy import *
from matplotlib.pyplot import *


fkirk = loadtxt("sampledmed_kirk.txt")
f43 = loadtxt("sampledmed_cut43.txt")
f = loadtxt("samplemed_current.txt")

rcParams['font.size'] = 15

def solweights(energies):
    return where(energies < 17, 0.5/0.7226, where(energies < 18, 0.5/0.8138, where(energies < 19, 0.5/0.8718, where(energies < 20, 0.5/0.965, 0.5))))


# Energy histograms
x = arange(17,89,2)
xerr = ones(len(x))
hkirk = histogram(fkirk[:, 1], bins = arange(16,90,2))
errorbar(x, hkirk[0], xerr = xerr, yerr = sqrt(hkirk[0]), label = "Kirk + precut", fmt = '.')
h43 = histogram(f43[:, 1], bins = arange(16,90,2))
errorbar(x, h43[0], xerr = xerr, yerr = sqrt(h43[0]), label = "New cut (60%)", fmt = '.')
h = histogram(f[:, 1], bins = arange(16,90,2))
errorbar(x, h[0], xerr = xerr, yerr = sqrt(h[0]), label = "New cut (76%)", fmt = '.')
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("energy_all.png", dpi = 300, bbox_inches = 'tight')

# deff > 500cm
clf()
x = arange(17,89,2)
xerr = ones(len(x))
hkirk = histogram(fkirk[:, 1], bins = arange(16,90,2))
hkirk2 = histogram(fkirk[fkirk[:, -3]>500, 1], bins = arange(16,90,2))
#h43 = histogram(f43[:, 1], bins = arange(16,90,2))
#errorbar(x, h43[0], xerr = xerr, yerr = sqrt(h43[0]), label = "New cut (60%)", fmt = '.')
#h = histogram(f[:, 1], bins = arange(16,90,2))
#errorbar(x, h[0], xerr = xerr, yerr = sqrt(h[0]), label = "New cut (76%)", fmt = '.')
hist(fkirk[:, 1], bins = arange(16,90,2), histtype = 'step', label = "New deff")
hist(fkirk[fkirk[:, -3]>500, 1], bins = arange(16,90,2), histtype = 'step', label = "deff > 500cm")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("deff_kirk.png", dpi = 300, bbox_inches = 'tight')
clf()
hist(f43[:, 1], bins = arange(16,90,2), histtype = 'step', label = "New deff")
hist(f43[f43[:, -3]>500, 1], bins = arange(16,90,2), histtype = 'step', label = "deff > 500cm")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("deff_cut43.png", dpi = 300, bbox_inches = 'tight')
clf()
hist(f[:, 1], bins = arange(16,90,2), histtype = 'step', label = "New deff")
hist(f[f[:, -3]>500, 1], bins = arange(16,90,2), histtype = 'step', label = "deff > 500cm")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("deff_current.png", dpi = 300, bbox_inches = 'tight')

# costhetasun < 0
clf()
x = arange(17,89,2)
xerr = ones(len(x))
hkirk = histogram(fkirk[:, 1], bins = arange(16,90,2))
hkirk2 = histogram(fkirk[fkirk[:, -4]<0, 1], bins = arange(16,90,2))
#h43 = histogram(f43[:, 1], bins = arange(16,90,2))
#errorbar(x, h43[0], xerr = xerr, yerr = sqrt(h43[0]), label = "New cut (60%)", fmt = '.')
#h = histogram(f[:, 1], bins = arange(16,90,2))
#errorbar(x, h[0], xerr = xerr, yerr = sqrt(h[0]), label = "New cut (76%)", fmt = '.')
hist(fkirk[:, 1], weights = solweights(fkirk[:, 1]), bins = arange(16,90,2), histtype = 'step', label = "Solar cut")
hist(fkirk[fkirk[:, -4] < 0, 1], bins = arange(16,90,2), histtype = 'step', label = r"$\cos\theta_\mathrm{sun}<0$")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("solar_kirk.png", dpi = 300, bbox_inches = 'tight')
clf()
hist(f43[:, 1], weights = solweights(f43[:, 1]), bins = arange(16,90,2), histtype = 'step', label = "Solar cut")
hist(f43[f43[:, -4]<0, 1], bins = arange(16,90,2), histtype = 'step', label = r"$\cos\theta_\mathrm{sun}<0$")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("solar_cut43.png", dpi = 300, bbox_inches = 'tight')
clf()
hist(f[:, 1], weights = solweights(f[:, 1]), bins = arange(16,90,2), histtype = 'step', label = "Solar cut")
hist(f[f[:, -4]<0, 1], bins = arange(16,90,2), histtype = 'step', label = r"$\cos\theta_\mathrm{sun}<0$")
legend()
xlabel("bsenergy (MeV)")
ylabel("Number of events")
savefig("solar_current.png", dpi = 300, bbox_inches = 'tight')

# Distance to wall and effwall
clf()
plot(fkirk[:, 1], fkirk[:, -3], '.')
xlim(16,90)
xlabel("bsenergy (MeV)")
ylabel("effwall (cm)")
savefig("energy_effwall_kirk.png", dpi = 300, bbox_inches = 'tight')
clf()
plot(f43[:, 1], f43[:, -3], '.')
xlim(16,90)
xlabel("bsenergy (MeV)")
ylabel("effwall (cm)")
savefig("energy_effwall_cut43.png", dpi = 300, bbox_inches = 'tight')
clf()
plot(f[:, 1], f[:, -3], '.')
xlim(16,90)
xlabel("bsenergy (MeV)")
ylabel("effwall (cm)")
savefig("energy_effwall_current.png", dpi = 300, bbox_inches = 'tight')
clf()
plot(fkirk[:, -2], fkirk[:, -3], '.')
xlabel("dwall (cm)")
ylabel("effwall (cm)")
savefig("dwall_effwall_kirk.png", dpi = 300, bbox_inches = 'tight')
show()
clf()
plot(f43[:, -2], f43[:, -3], '.')
xlabel("dwall (cm)")
ylabel("effwall (cm)")
savefig("dwall_effwall_cut43.png", dpi = 300, bbox_inches = 'tight')
show()
clf()
plot(f[:, -2], f[:, -3], '.')
xlabel("dwall (cm)")
ylabel("effwall (cm)")
savefig("dwall_effwall_current.png", dpi = 300, bbox_inches = 'tight')
show()
